# -*- coding: utf-8 -*-
# 문서 레지스트리: 원본파일 -> 슬러그/제목/카테고리/요약
DOCS = [
 dict(file="PAC Config 운영자 매뉴얼.docx", slug="pac-config", cat="기반설정",
      title="PAC Config 운영자 매뉴얼",
      summary="Business Package Config(ZTPAC_CONFIG)와 System Config(ZTPACSYS)의 전 설정키를 키별로 설명·참조 프로그램·영향도까지 정리한 설정 사전"),
 dict(file="권한 운영자 메뉴얼.docx", slug="authorization", cat="기반설정",
      title="권한 운영자 매뉴얼",
      summary="PAC 권한 체계 전반. SAP 권한 기본기, PAC 권한 체크 구조, 조직권한, Fiori 화면 권한, 실행/Posting User 개념과 트러블슈팅"),
 dict(file="조직마스터 운영자 메뉴얼.docx", slug="org-master", cat="기반설정",
      title="조직마스터 운영자 매뉴얼",
      summary="지역·국가·회사그룹 등 기초 조직 분류, Business Type 정의, 회사코드/사업영역 조직 마스터, 비즈니스 패키지 조직 배정과 상태 동기화 배치"),
 dict(file="Log 관리 프로세스 메뉴얼.docx", slug="log-management", cat="기반설정",
      title="Log 관리 프로세스 매뉴얼",
      summary="PAC 로그 설계 원칙, 공통 파라미터, PAC Log 매크로 적용법, ZCL_PAC_LOG 처리 구조, 로그 테이블과 조회 함수, 좀비 로그 정리"),
 dict(file="Activity Master 운영자 메뉴얼.docx", slug="activity-master", cat="마스터",
      title="Activity Master 운영자 매뉴얼",
      summary="Activity 3-Level 구조와 Activity Type별 정의 방법, 단계별 셋업 절차(STEP 1~6), 항목별 호출 Function 매핑, 트러블슈팅"),
 dict(file="모델링_운영자_메뉴얼.docx", slug="modeling", cat="마스터",
      title="모델링 운영자 매뉴얼",
      summary="표준 모델링(ZLPAC0030)과 조직 모델링(ZLPAC0040)을 통한 결산 프로세스 구성, 노드 정의·상속·선후행 관계 설정"),
 dict(file="결산일정_운영자_매뉴얼_v1.1.docx", slug="closing-schedule", cat="마스터",
      title="결산일정 운영자 매뉴얼",
      summary="Schedule ID 정의(ZLPAC7010), 월별 결산 캘린더(ZLPAC7030), 일정 배포(ZLPAC7100), Super User 등록, 일정 변경 및 알람 설정"),
 dict(file="Schedule Job 운영자 매뉴얼(정리).docx", slug="schedule-job", cat="마스터",
      title="Schedule Job 운영자 매뉴얼",
      summary="Job Schedule 정의(ZLPAC0500)·모니터링(ZLPAC0510)·월간 스케줄 관리(ZLPAC0520)·BP별 실행(ZLPAC0540)과 결산 시작 전 점검 항목"),
 dict(file="PAC_자동수행_운영자매뉴얼.docx", slug="auto-execution", cat="실행·자동화",
      title="PAC 자동수행 운영자 매뉴얼",
      summary="자동수행(XAUTO) 개념과 자동실행 흐름도, 수행 단계별 상세 프로세스, 프로그램 호출관계·선후행·영향도, 핵심 테이블과 설정 스위치"),
 dict(file="Auto_Trigger운영자_메뉴얼.docx", slug="auto-trigger", cat="실행·자동화",
      title="Auto Trigger 운영자 매뉴얼",
      summary="선행 Activity 완료 시 다른 BP·조직의 후행 작업을 자동 기동하는 Auto Trigger의 설정(ZLPAC0070), 엔진 동작 원리, 수동 재실행 절차"),
 dict(file="PAC_Batch_Job_생성_프로세스_운영자매뉴얼.docx", slug="batch-job", cat="실행·자동화",
      title="PAC Batch Job 생성 프로세스 운영자 매뉴얼",
      summary="PAC에서 배치 잡이 생성되는 경로별 프로세스 일람(Job 생성 함수와 호출 시점)"),
 dict(file="REWORK_운영자_메뉴얼_v1.1.docx", slug="rework", cat="실행·자동화",
      title="REWORK 운영자 매뉴얼",
      summary="완료된 Activity의 재작업 발생 감지 체계, REWORK Rule 활성화와 점검 주기, Linked Activity 동작, 모니터링 화면 기준 시나리오"),
 dict(file="Closing Inspection 운영자 메뉴얼_1.1.docx", slug="closing-inspection", cat="실행·자동화",
      title="Closing Inspection 운영자 매뉴얼",
      summary="결산점검 Category(ZLPAC5050)·Scenario(ZLPAC5060) 설정과 점검 수행·모니터링(ZLPAC5200), Financial Risk Validation 대시보드"),
 dict(file="모니터링_운영자_메뉴얼.docx", slug="monitoring", cat="모니터링·알림",
      title="모니터링 운영자 매뉴얼",
      summary="액티비티별·BP별·회사코드별·글로벌 프로세스별 진행현황 모니터링 프로그램, 실행시간 초과 모니터링, 관리자용 상태 관리(ZLPACSTATUSM)"),
 dict(file="PAC_To-Do_운영자_메뉴얼.docx", slug="todo", cat="모니터링·알림",
      title="PAC To-Do 운영자 매뉴얼",
      summary="To-Do 생성·완료 처리 개념과 유형별 프로세스, 관련 테이블·프로그램, 미완료 To-Do 처리 방법"),
 dict(file="메일링 운영자 메뉴얼.docx", slug="mailing", cat="모니터링·알림",
      title="메일링 운영자 매뉴얼",
      summary="PAC 메일 종류별 발송 구조와 관련 트랜잭션·함수·클래스, 운영자 발송 설정 절차, HTML 메일 양식 작성 원리, 트러블슈팅"),
 dict(file="공지사항 운영자 메뉴얼.docx", slug="notice", cat="모니터링·알림",
      title="공지사항 운영자 매뉴얼",
      summary="공지사항 관리 프로그램(ZLPAC0060)에서의 생성·수정·삭제와 첨부 파일 등록, APC를 통한 Fiori 실시간 반영 구조"),
 dict(file="APC 운영자 메뉴얼.docx", slug="apc", cat="연계",
      title="APC 운영자 매뉴얼",
      summary="ABAP Push Channel 기본 개념과 PAC이 사용하는 3개 APC(ZPAC/ZPAC_TODO/ZPAC_NOTICE)의 생성·환경 구성·상세 동작·점검 가이드"),
 dict(file="Fiori Action 호출 로직 운영자 메뉴얼.docx", slug="fiori-action", cat="연계",
      title="Fiori Action 호출 로직 운영자 매뉴얼",
      summary="Fiori 화면에서 호출되는 Action(권한체크·Start·Reset·Reset From Here·Confirm)의 처리 위치, 파라미터, 내부 로직과 오류 메시지"),
 dict(file="피오리_연계_SAP_GUI_호출_운영자_메뉴얼.docx", slug="fiori-sapgui-call", cat="연계",
      title="피오리 연계 SAP GUI 호출 운영자 매뉴얼",
      summary="Fiori에서 SAP GUI 트랜잭션을 호출하는 인터페이스(ZLPAC_FTCODE_MAIN)의 셀렉션 파라미터, 분기 로직, 호출 유형별 동작"),
 dict(file="Data Moigration 운영자 메뉴얼.docx", slug="data-migration", cat="이관·운영",
      title="Data Migration 운영자 매뉴얼",
      summary="ZLPACMIG010~050 이관 프로그램별 개요·화면·사용법, RFC Destination 일괄 수정 등 운영 주요 작업과 사전 점검 체크리스트"),
]
CATS = ["기반설정", "마스터", "실행·자동화", "모니터링·알림", "연계", "이관·운영"]
CAT_DESC = {
 "기반설정": "PAC 동작의 토대가 되는 설정·권한·조직·로그 체계",
 "마스터": "결산 프로세스를 정의하는 마스터 데이터와 일정 구성",
 "실행·자동화": "정의된 프로세스를 실행하고 자동으로 이어가는 엔진",
 "모니터링·알림": "수행 현황 조회와 사용자 알림(메일·To-Do·공지)",
 "연계": "Fiori 화면 및 실시간 푸시(APC) 연계 구조",
 "이관·운영": "설정·데이터 이관 및 운영 지원 도구",
}
SPLIT_THRESHOLD = 12000
